export function normaliseClub(raw: string): string {
  return raw
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/\([^)]*\)/g, ' ')
    .replace(/[–—-]/g, ' ')
    .replace(/\./g, '')
    .replace(/\b(fc|afc|wfc|rfc|sc|bsc|cf|nk|sk|if|bk|fk|mk|us|as|ac|ss|1\.|sv|vfb|fsv|rb|bv|tsg|vfl)\b/g, ' ')
    .replace(/\s+(b|c|ii|2|castilla|atletic|reserves?|youth|u21|u23)\s*$/i, ' ')
    .replace(/[^a-z0-9\s]/g, '')
    .replace(/\s+/g, ' ')
    .trim()
}

// Map of normalised club name → league
const CLUB_LEAGUE_MAP: Record<string, string> = buildMap()

function buildMap(): Record<string, string> {
  const entries: [string, string][] = [
    // ── Premier League (England) ──────────────────────────────────────────
    ['Arsenal', 'Premier League'],
    ['Aston Villa', 'Premier League'],
    ['Brentford', 'Premier League'],
    ['Brighton', 'Premier League'],
    ['Brighton & Hove Albion', 'Premier League'],
    ['Burnley', 'Premier League'],
    ['Chelsea', 'Premier League'],
    ['Crystal Palace', 'Premier League'],
    ['Everton', 'Premier League'],
    ['Fulham', 'Premier League'],
    ['Leeds United', 'Premier League'],
    ['Leicester City', 'Premier League'],
    ['Liverpool', 'Premier League'],
    ['Luton Town', 'Premier League'],
    ['Manchester City', 'Premier League'],
    ['Man City', 'Premier League'],
    ['Manchester United', 'Premier League'],
    ['Man United', 'Premier League'],
    ['Man Utd', 'Premier League'],
    ['Manchester Utd', 'Premier League'],
    ['Newcastle United', 'Premier League'],
    ['Nottingham Forest', 'Premier League'],
    ['Sheffield United', 'Premier League'],
    ['Southampton', 'Premier League'],
    ['Tottenham Hotspur', 'Premier League'],
    ['Spurs', 'Premier League'],
    ['West Ham United', 'Premier League'],
    ['Wolverhampton Wanderers', 'Premier League'],
    ['Wolves', 'Premier League'],
    ['Watford', 'Premier League'],
    ['Bournemouth', 'Premier League'],
    ['AFC Bournemouth', 'Premier League'],
    ['Sunderland', 'Premier League'],
    ['Bolton Wanderers', 'Premier League'],
    ['Stoke City', 'Premier League'],
    ['Swansea City', 'Premier League'],
    ['Hull City', 'Premier League'],
    ['Middlesbrough', 'Premier League'],
    ['Birmingham City', 'Premier League'],
    ['Blackburn Rovers', 'Premier League'],
    ['Charlton Athletic', 'Premier League'],
    ['Coventry City', 'Premier League'],
    ['Derby County', 'Premier League'],
    ['Ipswich Town', 'Premier League'],
    ['Norwich City', 'Premier League'],
    ['Queens Park Rangers', 'Premier League'],
    ['QPR', 'Premier League'],
    ['Wigan Athletic', 'Premier League'],

    // ── La Liga (Spain) ───────────────────────────────────────────────────
    ['Real Madrid', 'La Liga'],
    ['Barcelona', 'La Liga'],
    ['Barca', 'La Liga'],
    ['FC Barcelona', 'La Liga'],
    ['Atletico Madrid', 'La Liga'],
    ['Atlético Madrid', 'La Liga'],
    ['Atl. Madrid', 'La Liga'],
    ['Sevilla', 'La Liga'],
    ['Real Sociedad', 'La Liga'],
    ['Real Betis', 'La Liga'],
    ['Villarreal', 'La Liga'],
    ['Athletic Bilbao', 'La Liga'],
    ['Athletic Club', 'La Liga'],
    ['Valencia', 'La Liga'],
    ['Celta Vigo', 'La Liga'],
    ['Getafe', 'La Liga'],
    ['Osasuna', 'La Liga'],
    ['Girona', 'La Liga'],
    ['Mallorca', 'La Liga'],
    ['Las Palmas', 'La Liga'],
    ['Deportivo La Coruna', 'La Liga'],
    ['Deportivo de La Coruña', 'La Liga'],
    ['Malaga', 'La Liga'],
    ['Málaga', 'La Liga'],
    ['Rayo Vallecano', 'La Liga'],
    ['Almeria', 'La Liga'],
    ['Almería', 'La Liga'],
    ['Granada', 'La Liga'],
    ['Leganes', 'La Liga'],
    ['Leganés', 'La Liga'],
    ['Espanyol', 'La Liga'],
    ['RCD Espanyol', 'La Liga'],
    ['Cadiz', 'La Liga'],
    ['Cádiz', 'La Liga'],
    ['Alaves', 'La Liga'],
    ['Alavés', 'La Liga'],
    ['Deportivo Alaves', 'La Liga'],

    // ── Bundesliga (Germany) ──────────────────────────────────────────────
    ['Bayern Munich', 'Bundesliga'],
    ['FC Bayern Munich', 'Bundesliga'],
    ['Bayern München', 'Bundesliga'],
    ['Borussia Dortmund', 'Bundesliga'],
    ['BVB', 'Bundesliga'],
    ['Bayer Leverkusen', 'Bundesliga'],
    ['RB Leipzig', 'Bundesliga'],
    ['Borussia Monchengladbach', 'Bundesliga'],
    ['Borussia Mönchengladbach', 'Bundesliga'],
    ['Gladbach', 'Bundesliga'],
    ['Eintracht Frankfurt', 'Bundesliga'],
    ['Wolfsburg', 'Bundesliga'],
    ['VfL Wolfsburg', 'Bundesliga'],
    ['Freiburg', 'Bundesliga'],
    ['SC Freiburg', 'Bundesliga'],
    ['Union Berlin', 'Bundesliga'],
    ['1. FC Union Berlin', 'Bundesliga'],
    ['Mainz', 'Bundesliga'],
    ['1. FSV Mainz 05', 'Bundesliga'],
    ['Hoffenheim', 'Bundesliga'],
    ['TSG Hoffenheim', 'Bundesliga'],
    ['Werder Bremen', 'Bundesliga'],
    ['Stuttgart', 'Bundesliga'],
    ['VfB Stuttgart', 'Bundesliga'],
    ['Augsburg', 'Bundesliga'],
    ['FC Augsburg', 'Bundesliga'],
    ['Cologne', 'Bundesliga'],
    ['1. FC Köln', 'Bundesliga'],
    ['FC Cologne', 'Bundesliga'],
    ['Hertha Berlin', 'Bundesliga'],
    ['Hertha BSC', 'Bundesliga'],
    ['Schalke', 'Bundesliga'],
    ['FC Schalke 04', 'Bundesliga'],
    ['Hamburger SV', 'Bundesliga'],
    ['Hamburg', 'Bundesliga'],
    ['HSV', 'Bundesliga'],
    ['Hanover 96', 'Bundesliga'],
    ['Hannover 96', 'Bundesliga'],

    // ── Serie A (Italy) ───────────────────────────────────────────────────
    ['Juventus', 'Serie A'],
    ['Inter Milan', 'Serie A'],
    ['Inter', 'Serie A'],
    ['Internazionale', 'Serie A'],
    ['FC Internazionale', 'Serie A'],
    ['AC Milan', 'Serie A'],
    ['Milan', 'Serie A'],
    ['AS Roma', 'Serie A'],
    ['Roma', 'Serie A'],
    ['Lazio', 'Serie A'],
    ['SS Lazio', 'Serie A'],
    ['Napoli', 'Serie A'],
    ['SSC Napoli', 'Serie A'],
    ['Atalanta', 'Serie A'],
    ['Fiorentina', 'Serie A'],
    ['ACF Fiorentina', 'Serie A'],
    ['Torino', 'Serie A'],
    ['Bologna', 'Serie A'],
    ['Sassuolo', 'Serie A'],
    ['US Sassuolo', 'Serie A'],
    ['Udinese', 'Serie A'],
    ['Empoli', 'Serie A'],
    ['Hellas Verona', 'Serie A'],
    ['Verona', 'Serie A'],
    ['Cagliari', 'Serie A'],
    ['Lecce', 'Serie A'],
    ['Monza', 'Serie A'],
    ['Frosinone', 'Serie A'],
    ['Salernitana', 'Serie A'],
    ['US Salernitana', 'Serie A'],
    ['Spezia', 'Serie A'],
    ['Sampdoria', 'Serie A'],
    ['UC Sampdoria', 'Serie A'],
    ['Genoa', 'Serie A'],
    ['Parma', 'Serie A'],
    ['Palermo', 'Serie A'],

    // ── Ligue 1 (France) ──────────────────────────────────────────────────
    ['Paris Saint-Germain', 'Ligue 1'],
    ['PSG', 'Ligue 1'],
    ['Paris SG', 'Ligue 1'],
    ['Marseille', 'Ligue 1'],
    ['Olympique de Marseille', 'Ligue 1'],
    ['Lyon', 'Ligue 1'],
    ['Olympique Lyonnais', 'Ligue 1'],
    ['Monaco', 'Ligue 1'],
    ['AS Monaco', 'Ligue 1'],
    ['Lille', 'Ligue 1'],
    ['LOSC Lille', 'Ligue 1'],
    ['Nice', 'Ligue 1'],
    ['OGC Nice', 'Ligue 1'],
    ['Rennes', 'Ligue 1'],
    ['Stade Rennais', 'Ligue 1'],
    ['Strasbourg', 'Ligue 1'],
    ['RC Strasbourg', 'Ligue 1'],
    ['Lens', 'Ligue 1'],
    ['RC Lens', 'Ligue 1'],
    ['Montpellier', 'Ligue 1'],
    ['Nantes', 'Ligue 1'],
    ['FC Nantes', 'Ligue 1'],
    ['Bordeaux', 'Ligue 1'],
    ['Girondins de Bordeaux', 'Ligue 1'],
    ['Saint-Etienne', 'Ligue 1'],
    ['AS Saint-Étienne', 'Ligue 1'],
    ['Toulouse', 'Ligue 1'],
    ['Brest', 'Ligue 1'],
    ['Stade Brestois', 'Ligue 1'],
    ['Reims', 'Ligue 1'],
    ['Stade de Reims', 'Ligue 1'],
    ['Metz', 'Ligue 1'],
    ['FC Metz', 'Ligue 1'],
    ['Lorient', 'Ligue 1'],
    ['Clermont', 'Ligue 1'],
    ['Clermont Foot', 'Ligue 1'],
    ['Troyes', 'Ligue 1'],
    ['ESTAC Troyes', 'Ligue 1'],
    ['Angers', 'Ligue 1'],

    // ── Eredivisie (Netherlands) ──────────────────────────────────────────
    ['Ajax', 'Eredivisie'],
    ['AFC Ajax', 'Eredivisie'],
    ['PSV Eindhoven', 'Eredivisie'],
    ['PSV', 'Eredivisie'],
    ['Feyenoord', 'Eredivisie'],
    ['AZ Alkmaar', 'Eredivisie'],
    ['AZ', 'Eredivisie'],
    ['Utrecht', 'Eredivisie'],
    ['FC Utrecht', 'Eredivisie'],
    ['Vitesse', 'Eredivisie'],
    ['SBV Vitesse', 'Eredivisie'],
    ['Twente', 'Eredivisie'],
    ['FC Twente', 'Eredivisie'],
    ['Groningen', 'Eredivisie'],
    ['FC Groningen', 'Eredivisie'],
    ['Willem II', 'Eredivisie'],
    ['NEC Nijmegen', 'Eredivisie'],
    ['NEC', 'Eredivisie'],
    ['Heracles', 'Eredivisie'],
    ['Heracles Almelo', 'Eredivisie'],
    ['Fortuna Sittard', 'Eredivisie'],

    // ── Primeira Liga (Portugal) ──────────────────────────────────────────
    ['Benfica', 'Primeira Liga'],
    ['SL Benfica', 'Primeira Liga'],
    ['Porto', 'Primeira Liga'],
    ['FC Porto', 'Primeira Liga'],
    ['Sporting CP', 'Primeira Liga'],
    ['Sporting Lisbon', 'Primeira Liga'],
    ['Braga', 'Primeira Liga'],
    ['SC Braga', 'Primeira Liga'],
    ['Vitoria Guimaraes', 'Primeira Liga'],
    ['Vitória SC', 'Primeira Liga'],
    ['Boavista', 'Primeira Liga'],
    ['Maritimo', 'Primeira Liga'],
    ['CS Maritimo', 'Primeira Liga'],
    ['Pacos de Ferreira', 'Primeira Liga'],

    // ── Pro League (Belgium) ──────────────────────────────────────────────
    ['Club Brugge', 'Pro League'],
    ['Anderlecht', 'Pro League'],
    ['RSC Anderlecht', 'Pro League'],
    ['Gent', 'Pro League'],
    ['KAA Gent', 'Pro League'],
    ['Standard Liège', 'Pro League'],
    ['Standard Liege', 'Pro League'],
    ['Standard de Liège', 'Pro League'],
    ['Genk', 'Pro League'],
    ['KRC Genk', 'Pro League'],
    ['Bruges', 'Pro League'],

    // ── Super Lig (Turkey) ────────────────────────────────────────────────
    ['Galatasaray', 'Süper Lig'],
    ['Fenerbahce', 'Süper Lig'],
    ['Fenerbahçe', 'Süper Lig'],
    ['Besiktas', 'Süper Lig'],
    ['Beşiktaş', 'Süper Lig'],
    ['Trabzonspor', 'Süper Lig'],
    ['Bursaspor', 'Süper Lig'],

    // ── Russian Premier League ────────────────────────────────────────────
    ['Spartak Moscow', 'Russian Premier League'],
    ['CSKA Moscow', 'Russian Premier League'],
    ['Zenit St Petersburg', 'Russian Premier League'],
    ['Zenit Saint Petersburg', 'Russian Premier League'],
    ['Zenit', 'Russian Premier League'],
    ['Lokomotiv Moscow', 'Russian Premier League'],
    ['Dynamo Moscow', 'Russian Premier League'],

    // ── Major League Soccer (USA) ─────────────────────────────────────────
    ['LA Galaxy', 'MLS'],
    ['Los Angeles Galaxy', 'MLS'],
    ['Inter Miami', 'MLS'],
    ['Inter Miami CF', 'MLS'],
    ['New York City FC', 'MLS'],
    ['NYCFC', 'MLS'],
    ['New York Red Bulls', 'MLS'],
    ['Chicago Fire', 'MLS'],
    ['Chicago Fire FC', 'MLS'],
    ['Seattle Sounders', 'MLS'],
    ['Seattle Sounders FC', 'MLS'],
    ['Portland Timbers', 'MLS'],
    ['Atlanta United', 'MLS'],
    ['Atlanta United FC', 'MLS'],
    ['DC United', 'MLS'],
    ['D.C. United', 'MLS'],
    ['Colorado Rapids', 'MLS'],
    ['Real Salt Lake', 'MLS'],
    ['Toronto FC', 'MLS'],
    ['Vancouver Whitecaps', 'MLS'],
    ['Vancouver Whitecaps FC', 'MLS'],
    ['Orlando City', 'MLS'],
    ['Orlando City SC', 'MLS'],
    ['Columbus Crew', 'MLS'],

    // ── Argentine Primera División ────────────────────────────────────────
    ['Boca Juniors', 'Argentine Primera División'],
    ['River Plate', 'Argentine Primera División'],
    ['Racing Club', 'Argentine Primera División'],
    ['Independiente', 'Argentine Primera División'],
    ['San Lorenzo', 'Argentine Primera División'],
    ['Estudiantes', 'Argentine Primera División'],
    ['Velez Sarsfield', 'Argentine Primera División'],
    ['Vélez Sarsfield', 'Argentine Primera División'],
    ["Newell's Old Boys", 'Argentine Primera División'],
    ['Newells Old Boys', 'Argentine Primera División'],
    ['Rosario Central', 'Argentine Primera División'],

    // ── Brasileirão (Brazil) ──────────────────────────────────────────────
    ['Flamengo', 'Brasileirão'],
    ['CR Flamengo', 'Brasileirão'],
    ['Palmeiras', 'Brasileirão'],
    ['SE Palmeiras', 'Brasileirão'],
    ['Sao Paulo', 'Brasileirão'],
    ['São Paulo', 'Brasileirão'],
    ['Corinthians', 'Brasileirão'],
    ['Sport Club Corinthians', 'Brasileirão'],
    ['Santos', 'Brasileirão'],
    ['Atletico Mineiro', 'Brasileirão'],
    ['Atlético Mineiro', 'Brasileirão'],
    ['Cruzeiro', 'Brasileirão'],
    ['Gremio', 'Brasileirão'],
    ['Grêmio', 'Brasileirão'],
    ['Internacional', 'Brasileirão'],
    ['Sport Club Internacional', 'Brasileirão'],
    ['Fluminense', 'Brasileirão'],
    ['Vasco da Gama', 'Brasileirão'],
    ['CR Vasco da Gama', 'Brasileirão'],
    ['Botafogo', 'Brasileirão'],

    // ── Scottish Premiership ──────────────────────────────────────────────
    ['Celtic', 'Scottish Premiership'],
    ['Celtic FC', 'Scottish Premiership'],
    ['Rangers', 'Scottish Premiership'],
    ['Rangers FC', 'Scottish Premiership'],
    ['Hearts', 'Scottish Premiership'],
    ['Heart of Midlothian', 'Scottish Premiership'],
    ['Hibernian', 'Scottish Premiership'],
    ['Aberdeen', 'Scottish Premiership'],
    ['Dundee United', 'Scottish Premiership'],
    ['Motherwell', 'Scottish Premiership'],

    // ── Saudi Pro League ──────────────────────────────────────────────────
    ['Al-Nassr', 'Saudi Pro League'],
    ['Al Nassr', 'Saudi Pro League'],
    ['Al-Hilal', 'Saudi Pro League'],
    ['Al Hilal', 'Saudi Pro League'],
    ['Al-Ittihad', 'Saudi Pro League'],
    ['Al Ittihad', 'Saudi Pro League'],
    ['Al-Ahli', 'Saudi Pro League'],
    ['Al Ahli', 'Saudi Pro League'],

    // ── J-League (Japan) ─────────────────────────────────────────────────
    ['Kashima Antlers', 'J-League'],
    ['Gamba Osaka', 'J-League'],
    ['Urawa Reds', 'J-League'],
    ['Urawa Red Diamonds', 'J-League'],
  ]

  const map: Record<string, string> = {}
  for (const [club, league] of entries) {
    const key = normaliseClub(club)
    if (key) {
      map[key] = league
    }
  }
  return map
}

export function getClubLeague(clubName: string): string | null {
  const key = normaliseClub(clubName)
  return CLUB_LEAGUE_MAP[key] ?? null
}
